<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import Icon from './Icon.vue';
import FoodArt from './FoodArt.vue';
import { catalog, copy, food, initialMeals, basePlan, demoDate } from './data.js';

const nav = [{id:'today',label:'今天',icon:'today'},{id:'nutrition',label:'饮食',icon:'food'},{id:'training',label:'训练',icon:'train'},{id:'history',label:'历史',icon:'history'},{id:'profile',label:'我的',icon:'user'}];
const page = ref('today'), trail = ref([]), date = ref(demoDate), historyDate = ref(demoDate), historyTab = ref('记录'), historyFilter = ref('全部');
const meals = ref(initialMeals()), currentId = ref('lunch'), notes = ref(''), photo = ref(''), selectionFile = ref(''), scenario = ref('normal'), notice = ref('');
const prefs = reactive({ auto: true, consent: true, reminder: false });
const foods = ref(copy(catalog)), query = ref(''), category = ref('全部'), selected = ref([]), pickerTarget = ref(null), replaceKey = ref(null), pickerTime = ref('12:20');
const trainingDrafts = new Map();
let trainingDraftKey = '';
const plansByDate = reactive({[demoDate]:copy(basePlan)});
const plan = computed({get:()=>plansByDate[date.value]||[],set:value=>plansByDate[date.value]=value});
const planAvailable = computed({get:()=>Boolean(plansByDate[date.value]),set:value=>{if(value)plansByDate[date.value]??=copy(basePlan);else delete plansByDate[date.value];}});
const trainingDraft = ref([]), trainingTime = ref('18:30'), trainingMode = ref('record'), trainingEditId = ref(null), recordLink = ref(false);
const records = ref([{id:'training-sample',date:demoDate,time:'07:30',linked:true,items:[{...copy(basePlan[0]),sets:2}]}]);
const measurements = ref([{id:1,date:'2026-09-01',value:66.2},{id:2,date:'2026-09-05',value:66.0},{id:3,date:'2026-09-09',value:65.8},{id:4,date:'2026-09-13',value:65.5},{id:5,date:demoDate,value:65.4}]);
const signupStep = ref(0), authMode = ref('register');
const signup = reactive({name:'',password:'',height:'',weight:'',activity:'日常走动较多',goal:'保持体重',auto:false,consent:false,reminder:false});
const profileName = ref('体验账号'), profileGoal = ref('保持体重');
const dialog = ref(null), sheet = reactive({title:'',description:'',fields:[],label:'保存',danger:false,action:null,error:''});
const timers = new Set(), urls = new Set();
const active = computed(()=> nav.some(n=>n.id===page.value)?page.value:['capture','meal','picker'].includes(page.value)?'nutrition':['training-editor','plans'].includes(page.value)?'training':['body','settings','signup','prototype'].includes(page.value)?'profile':'today');
const mainPage = computed(()=>nav.some(n=>n.id===page.value));
const currentMeal = computed(()=>meals.value.find(m=>m.id===currentId.value));
const dayMeals = computed(()=>meals.value.filter(m=>m.date===date.value).sort((a,b)=>b.time.localeCompare(a.time)));
const dayRecords = computed(()=>records.value.filter(r=>r.date===date.value));
const sum = (items,key='energy')=> items.length&&items.every(f=>f[key]===null)?'—':Math.round(items.reduce((n,f)=>n+(Number(f[key])||0),0)*10)/10;
const totals = computed(()=>['energy','protein','carbs','fat'].map(k=>sum(dayMeals.value.flatMap(m=>m.items),k)));
const metrics = [{key:'protein',name:'蛋白质',class:'protein'},{key:'carbs',name:'碳水',class:'carbs'},{key:'fat',name:'脂肪',class:'fat'}];
const latestBody = computed(()=>[...measurements.value].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id)[0]);
const matchingFoods = computed(()=>foods.value.filter(f=>(category.value==='全部'||category.value==='常用'&&f.common||category.value===f.category)&&(!query.value.trim()||(f.name+f.subtitle+f.aliases).includes(query.value.trim()))).sort((a,b)=>Number(b.common)-Number(a.common)));
const historyMeals = computed(()=>meals.value.filter(m=>m.date===historyDate.value));
const historyRecords = computed(()=>records.value.filter(r=>r.date===historyDate.value));
const historyBody = computed(()=>measurements.value.filter(m=>m.date===historyDate.value));
const completedSets = computed(()=>dayRecords.value.filter(r=>r.linked).flatMap(r=>r.items).reduce((n,i)=>n+(Number(i.sets)||0),0));
const plannedSets = computed(()=>plan.value.reduce((n,i)=>n+(Number(i.sets)||0),0));
const planProgress = item => Math.min(Number(item.sets)||0,dayRecords.value.filter(r=>r.linked).flatMap(r=>r.items).filter(i=>i.id===item.id).reduce((s,i)=>s+(Number(i.sets)||0),0));
const remainingSets = computed(()=>plan.value.reduce((s,i)=>s+Math.max(0,(Number(i.sets)||0)-planProgress(i)),0));
const bodyPoints = computed(()=>{
 const rows=[...measurements.value].sort((a,b)=>a.date.localeCompare(b.date)); if(!rows.length)return '';
 const min=Math.min(...rows.map(m=>m.value))-.2,max=Math.max(...rows.map(m=>m.value))+.2;
 return rows.map((r,i)=>`${20+i*280/Math.max(1,rows.length-1)},${140-(r.value-min)/(max-min)*110}`).join(' ');
});
function displayDate(value){ const [y,m,d]=value.split('-');return `${Number(m)}月${Number(d)}日`; }
function shortDate(value){return value.slice(5).replace('-','/');}
function cacheTrainingDraft(){if(page.value==='training-editor'&&trainingDraftKey)trainingDrafts.set(trainingDraftKey,{items:copy(trainingDraft.value),time:trainingTime.value,linked:recordLink.value});}
function go(to){cacheTrainingDraft();trail.value.push({page:page.value,scroll:window.scrollY});page.value=to;notice.value='';window.scrollTo(0,0);}
function switchPage(to){cacheTrainingDraft();if(to==='today')date.value=demoDate;trail.value=[];page.value=to;notice.value='';window.scrollTo(0,0);}
function back(){cacheTrainingDraft();const entry=trail.value.pop();page.value=entry?.page||active.value;notice.value='';nextTick(()=>window.scrollTo(0,entry?.scroll||0));}
function openMeal(meal){currentId.value=meal.id;go('meal');}
function startCapture(){photo.value='';selectionFile.value='';notes.value='';go('capture');}
function tell(message){notice.value=message;}
function schedule(fn,ms){const id=setTimeout(()=>{timers.delete(id);fn();},ms);timers.add(id);}
async function openSheet(title,fields,action,{description='',label='保存',danger=false}={}){
 Object.assign(sheet,{title,fields,action,description,label,danger,error:''});await nextTick();dialog.value.showModal();
 const first=dialog.value.querySelector('input,select');if(first)first.focus({preventScroll:true});
}
function closeSheet(){dialog.value.close();}
function submitSheet(){const values=Object.fromEntries(sheet.fields.map(f=>[f.name,f.value]));if(sheet.action?.(values)!==false)closeSheet();}
const field=(name,label,value,type='text',extra={})=>({name,label,value,type,required:true,...extra});
function maySave(){if(scenario.value==='save-failed'){const message=dialog.value?.open?'模拟保存失败，输入仍保留。可恢复正常后重试。':'模拟保存失败，输入仍保留。请在“原型”中切回正常，再保存。';if(dialog.value?.open)sheet.error=message;else tell(message);return false;}sheet.error='';return true;}
function editPortion(item){openSheet(item.name,[field('amount',`食用量（${item.unit}）`,item.amount,'number',{min:0.01,step:'any'})],values=>{
 if(!maySave())return false;const amount=Number(values.amount),ratio=amount/item.amount;for(const key of ['energy','protein','carbs','fat'])if(item[key]!==null)item[key]=Math.round(item[key]*ratio*10)/10;item.amount=amount;
},{description:'营养随份量一起调整。此处为示例估算。',label:'保存份量'});}
function editMeal(){const m=currentMeal.value;openSheet('餐食信息',[field('name','名称',m.name),field('date','日期',m.date,'date'),field('time','时间',m.time,'time'),field('note','备注',m.note,'text',{required:false})],v=>{if(!maySave())return false;Object.assign(m,v);},{label:'保存修改'});}
function deleteMeal(meal){const m=meal?.id?meal:currentMeal.value;openSheet('删除这餐？',[],()=>{if(!maySave())return false;meals.value=meals.value.filter(x=>x.id!==m.id);if(page.value==='meal')back();},{description:`${m.name}和相关照片将被删除，不能恢复。其他餐食不受影响。原型只删除示例。`,label:'删除餐食',danger:true});}
function removeFood(item){currentMeal.value.items=currentMeal.value.items.filter(f=>f.key!==item.key);}
function choosePhoto(event){const file=event.target.files?.[0];if(!file)return;event.target.value='';if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)){tell('暂不支持这种图片格式，请选择 JPG、PNG、WebP 或 GIF。');return;}if(file.size>20*1024*1024){tell('图片超过 20 MB，请换一张较小的图片。');return;}const url=URL.createObjectURL(file);urls.add(url);photo.value=url;selectionFile.value=file.name;notice.value='';}
function demoPhoto(){photo.value='/assets/sample-lunch.png';selectionFile.value='公开示例餐盘';notice.value='';}
function uploadPhoto(){
 if(!photo.value)return;if(scenario.value==='upload-failed'){tell('模拟上传失败。照片仍在，可重试或返回重新选择。');return;}
 const m={id:crypto.randomUUID(),date:date.value,time:pickerTime.value,name:'照片餐食',photo:photo.value,note:notes.value,items:[],status:prefs.auto?'processing':'waiting',source:'照片估算'};
 meals.value.unshift(m);currentId.value=m.id;page.value='meal';if(prefs.auto)runRecognition(m);
}
function runRecognition(m){m.status='processing';schedule(()=>{if(!meals.value.some(x=>x.id===m.id))return;if(scenario.value==='recognition-failed'){m.status='failed';return;}
 const items=['scramble','potato','broccoli','pineapple','berries'].map(food);if(m.items.length){m.status='replacement';m.candidate=items;}else{m.items=items;m.status='ready';m.name='鸡蛋、蔬菜与水果';}
 },1500);}
function recognize(m){if(!prefs.consent){openSheet('使用照片识别',[],()=>{prefs.consent=true;runRecognition(m);},{description:'正式版会发送所选照片给模型服务。本原型仅模拟，不上传照片。',label:'同意并模拟识别'});}else runRecognition(m);}
function useCandidate(){const m=currentMeal.value;openSheet('替换当前食物？',[],()=>{m.items=copy(m.candidate);m.candidate=null;m.status='ready';},{description:'将用本次的炒鸡蛋、烤土豆、西兰花、菠萝、草莓与蓝莓示例替换当前全部食物。',label:'替换食物'});}
function startPicker(target=null,key=null){pickerTarget.value=target;replaceKey.value=key;query.value='';category.value='全部';if(target||key)selected.value=[];go('picker');}
function selectFood(item){if(replaceKey.value){const m=meals.value.find(x=>x.id===pickerTarget.value),index=m.items.findIndex(x=>x.key===replaceKey.value);const newItem={...copy(item),key:crypto.randomUUID()};openSheet('替换为'+item.name,[field('amount',`食用量（${item.unit}）`,item.amount,'number',{min:0.01,step:'any'})],v=>{if(!maySave())return false;const ratio=Number(v.amount)/item.amount;for(const k of ['energy','protein','carbs','fat'])if(newItem[k]!==null)newItem[k]=Math.round(newItem[k]*ratio*10)/10;newItem.amount=Number(v.amount);m.items.splice(index,1,newItem);back();},{label:'替换这一项'});return;}
 if(selected.value.some(f=>f.id===item.id))selected.value=selected.value.filter(f=>f.id!==item.id);else selected.value.push({...copy(item),key:crypto.randomUUID()});}
function saveSelection(){if(!selected.value.length||!maySave())return;let m=meals.value.find(x=>x.id===pickerTarget.value);const existing=Boolean(m);if(m)m.items.push(...copy(selected.value));else{m={id:crypto.randomUUID(),date:date.value,time:pickerTime.value,name:'手动记录',photo:null,note:'',items:copy(selected.value),source:'手动记录',status:'ready'};meals.value.unshift(m);}selected.value=[];currentId.value=m.id;if(existing)back();else page.value='meal';}
function customFood(){openSheet('补充食物',[field('name','食物名称',query.value),field('amount','份量',1,'number',{min:.01,step:'any'}),field('unit','单位','份')],v=>{const item={id:crypto.randomUUID(),key:crypto.randomUUID(),name:v.name,amount:Number(v.amount),unit:v.unit,energy:null,protein:null,carbs:null,fat:null,kind:'vegetable',category:'家常菜',subtitle:'营养暂未知',aliases:'',common:true};foods.value.push(item);selected.value.push(copy(item));},{description:'不知道营养也可以记录，不会按零计算。',label:'加入已选'});}
function beginTraining(source='plan',record=null){trainingMode.value='record';trainingEditId.value=record?.id||null;trainingDraftKey=`record:${record?.id||date.value+':'+source}`;const draft=trainingDrafts.get(trainingDraftKey);recordLink.value=draft?.linked??record?.linked??source==='plan';trainingDraft.value=copy(draft?.items||record?.items||(source==='blank'?[]:source==='last'?records.value.at(-1)?.items||basePlan:source==='saved'?basePlan:plan.value));trainingTime.value=draft?.time||record?.time||'18:30';go('training-editor');}
function editPlan(){trainingMode.value='plan';trainingEditId.value=null;trainingDraftKey=`plan:${date.value}`;trainingDraft.value=copy(trainingDrafts.get(trainingDraftKey)?.items||plan.value);go('training-editor');}
function editExercise(item){openSheet(item.name,[field('sets','组数（可不填）',item.sets,'number',{min:1,required:false}),field('reps','每组次数（可不填）',item.reps,'number',{min:1,required:false}),field('weight','重量 kg（自重填 0）',item.weight,'number',{min:0,step:.5,required:false})],v=>{for(const k of ['sets','reps','weight'])item[k]=v[k]===''?null:Number(v[k]);},{label:'保存动作'});}
function addExercise(){openSheet('添加动作',[field('name','动作名称','俯卧撑'),field('sets','组数',3,'number',{min:1}),field('reps','每组次数',10,'number',{min:1})],v=>trainingDraft.value.push({id:crypto.randomUUID(),name:v.name,area:'自选动作',sets:Number(v.sets),reps:Number(v.reps),weight:0}));}
function saveTraining(){if(!trainingDraft.value.length||!maySave())return;if(trainingMode.value==='plan'){plan.value=copy(trainingDraft.value);planAvailable.value=true;}else{const r={id:trainingEditId.value||crypto.randomUUID(),date:date.value,time:trainingTime.value,items:copy(trainingDraft.value),linked:recordLink.value};const index=records.value.findIndex(x=>x.id===r.id);if(index>=0)records.value[index]=r;else records.value.push(r);}trainingDrafts.delete(trainingDraftKey);trainingDraftKey='';back();}
function deleteTraining(record){openSheet('删除训练记录？',[],()=>{records.value=records.value.filter(r=>r.id!==record.id);},{description:'只删除这条实际记录，不改变训练计划。',label:'删除记录',danger:true});}
function editBody(row=null){openSheet(row?'修改这次测量':'记录体重',[field('value','体重 kg',row?.value||latestBody.value?.value||'','number',{min:1,max:500,step:.1}),field('date','测量日期',row?.date||demoDate,'date')],v=>{if(!maySave())return false;if(row){row.value=Number(v.value);row.date=v.date;}else measurements.value.push({id:Date.now(),date:v.date,value:Number(v.value)});},{label:row?'保存修改':'保存测量'});}
function deleteBody(row){openSheet('删除这次测量？',[],()=>{measurements.value=measurements.value.filter(r=>r.id!==row.id);},{description:`${displayDate(row.date)} · ${row.value} kg，不影响其他测量。`,label:'删除测量',danger:true});}
function simpleInfo(title,description){openSheet(title,[],null,{description,label:'知道了'});}
function renameProfile(){openSheet('资料与目标',[field('name','称呼',profileName.value),field('goal','目标方向',profileGoal.value,'select',{options:['保持体重','减少体重','增加体重']})],v=>{profileName.value=v.name;profileGoal.value=v.goal;});}
function signupNext(){if(signupStep.value===0){if(signup.auto&&!signup.consent){tell('开启照片识别前，请先同意照片发送范围。');return;}prefs.auto=signup.auto;prefs.consent=signup.consent;}if(signupStep.value<4)signupStep.value++;else finishSignup();}
function finishSignup(){profileName.value=signup.name||'体验账号';profileGoal.value=signup.goal;prefs.reminder=signup.reminder;if(Number(signup.weight)>0)measurements.value.push({id:Date.now(),date:demoDate,value:Number(signup.weight)});switchPage('today');tell('示例首次设置已完成，未创建真实账号。');}
function toggleAuto(){if(prefs.auto&&!prefs.consent){prefs.auto=false;openSheet('照片识别授权',[],()=>{prefs.consent=true;prefs.auto=true;},{description:'正式版会发送所选照片到模型服务。此处只演示偏好，不调用模型。',label:'同意'});}}
function resetDemo(){window.location.reload();}
function setEmpty(){date.value='2026-09-19';switchPage('nutrition');}
function viewHistoryMeal(m){openMeal(m);}
function changeSearch(){if(query.value)category.value='全部';}
function handleKey(event){if(event.key==='Escape'&&dialog.value?.open)closeSheet();}
function resizeViewport(){const viewport=window.visualViewport;document.documentElement.style.setProperty('--visible-height',`${viewport?.height||window.innerHeight}px`);document.documentElement.style.setProperty('--keyboard-inset',`${Math.max(0,window.innerHeight-(viewport?viewport.height+viewport.offsetTop:window.innerHeight))}px`);}
onMounted(()=>{window.addEventListener('keydown',handleKey);window.visualViewport?.addEventListener('resize',resizeViewport);resizeViewport();});
onBeforeUnmount(()=>{window.removeEventListener('keydown',handleKey);window.visualViewport?.removeEventListener('resize',resizeViewport);for(const t of timers)clearTimeout(t);for(const url of urls)URL.revokeObjectURL(url);});
</script>

<template>
 <div class="app-shell">
  <aside class="desktop-nav"><div class="brand"><span class="brand-icon"><Icon name="leaf"/></span><span>Exercise App<small>饮食与训练，轻松记录</small></span></div><nav aria-label="桌面导航"><button v-for="item in nav" :key="item.id" :class="{active:active===item.id}" @click="switchPage(item.id)"><Icon :name="item.icon"/>{{item.label}}<Icon name="arrow"/></button></nav><div class="sidebar-footer"><span class="avatar">我</span><div>{{profileName}}<small>独立交互原型</small></div></div></aside>
  <div class="main-column">
   <div class="prototype-bar"><span><span class="status-dot"></span>交互原型 · 示例数据</span><button @click="go('prototype')"><Icon name="settings"/>原型</button></div>
   <header class="page-header"><div v-if="mainPage"><p class="eyebrow">{{page==='today'?'9月18日 · 星期五':page==='nutrition'?'把吃过的，轻松记下来':page==='training'?'按自己的节奏来':page==='history'?'每一次记录，都在这里':'你的身体，你的节奏'}}</p><h1>{{nav.find(n=>n.id===page)?.label}}</h1></div><button v-else class="back" @click="back"><Icon name="back"/>返回</button><button v-if="page==='today'" class="avatar" aria-label="打开我的" @click="switchPage('profile')">我</button><label v-else-if="['nutrition','training'].includes(page)" class="date-button"><Icon name="calendar"/><input v-model="date" type="date" aria-label="查看日期"/></label><span v-else-if="!mainPage" class="subpage-label">{{active==='nutrition'?'饮食记录':active==='training'?'训练记录':'Exercise App'}}</span></header>
   <div v-if="notice" class="notice" role="alert"><Icon name="info"/><span>{{notice}}</span><button class="icon-button" aria-label="关闭提示" @click="notice='' "><Icon name="close"/></button></div>
   <main :class="['content',{'editor-content':!mainPage}]">
    <template v-if="page==='today'">
     <div class="home-grid"><section class="nutrition-hero surface"><div class="section-heading"><h2>今天吃了多少</h2><span class="quiet-tag">已记录</span></div><div class="hero-value"><div><strong>{{totals[0].toLocaleString()}}</strong><span>千卡</span><small>来自 {{dayMeals.length}} 餐记录</small></div><div class="plate-art"><FoodArt kind="broccoli"/><FoodArt kind="egg"/><FoodArt kind="rice"/></div></div><div class="macro-grid"><div v-for="(m,i) in metrics" :key="m.key"><span :class="['macro-dot',m.class]"></span><small>{{m.name}}</small><strong>{{totals[i+1]}}<em>克</em></strong></div></div><div class="photo-actions"><button class="primary" @click="startCapture"><Icon name="camera"/>拍照记一餐</button><button class="secondary square" aria-label="从相册记餐" @click="startCapture"><Icon name="image"/></button></div><button class="last-meal" @click="switchPage('nutrition')"><Icon name="clock"/><span>{{dayMeals[0]?`上一餐 ${dayMeals[0].time} · ${dayMeals[0].name}`:'还没有餐食记录'}}</span><Icon name="arrow"/></button></section>
     <section class="training-home surface"><div class="section-heading"><h2>今天的训练</h2><span class="quiet-tag">{{planAvailable?'有计划':'自由记录'}}</span></div><div class="training-feature"><div class="exercise-visual"><Icon name="train"/></div><div><h3>{{planAvailable?'全身力量训练':'练了什么，记下来'}}</h3><p>{{planAvailable?'深蹲 · 划船 · 推举':dayRecords.length?`${dayRecords.length} 条实际记录`:'有无计划，都可以记录'}}</p></div></div><template v-if="planAvailable"><div class="progress-line"><span>已记录 <b>{{completedSets}}</b> 组</span><span>计划还剩 {{remainingSets}} 组</span></div><div class="progress-track"><span :style="{width:Math.min(100,(plannedSets-remainingSets)/Math.max(1,plannedSets)*100)+'%'}"></span></div></template><button class="secondary full" @click="beginTraining(planAvailable?'plan':'blank')"><Icon name="plus"/>记录训练</button><button class="text-button centered" @click="switchPage('training')">{{planAvailable?'查看今天计划':'查看训练记录'}}<Icon name="arrow"/></button></section></div>
    </template>

    <template v-else-if="page==='nutrition'">
     <section class="nutrition-strip surface"><div><small>已记录能量</small><strong>{{totals[0]}}<em>千卡</em></strong></div><div class="compact-macros"><span v-for="(m,i) in metrics" :key="m.key">{{m.name}}<b>{{totals[i+1]}}<em>g</em></b></span></div></section>
     <div class="capture-actions"><button class="primary" @click="startCapture"><Icon name="camera"/>拍照</button><button class="secondary" @click="startCapture"><Icon name="image"/>相册</button><button class="text-button" @click="startPicker()"><Icon name="plus"/>手动添加</button></div>
     <div class="section-heading"><h2>这一天的餐食</h2><span class="muted">{{dayMeals.length}} 餐</span></div>
     <div v-if="!dayMeals.length" class="empty"><div class="empty-art"><FoodArt kind="rice"/></div><h3>这一天还没记餐</h3><p>拍一张照片，或选几样吃过的食物。</p><button class="primary" @click="startCapture">记录第一餐</button></div>
     <div v-else class="meal-grid"><article v-for="meal in dayMeals" :key="meal.id" class="meal-card surface"><button class="meal-main" @click="openMeal(meal)"><img v-if="meal.photo" :src="meal.photo" alt="公开示例餐食照片" width="640" height="480"/><div v-else class="meal-illustration"><FoodArt :kind="meal.items[0]?.kind||'rice'"/></div><div class="meal-text"><small>{{meal.time}}<span class="tiny-dot">·</span>{{meal.source}}</small><h3>{{meal.name}}</h3><p>{{meal.items.map(f=>f.name).join('、')||'还没有食物'}}</p><strong>{{meal.items.length?sum(meal.items):'—'}}<em>千卡</em></strong><span v-if="meal.status==='processing'" class="state-label">识别中…</span><span v-else-if="meal.status==='failed'" class="error-text">识别未完成</span></div><Icon name="arrow"/></button><button v-if="!meal.items.length&&meal.status!=='processing'" class="text-button meal-empty-delete" @click="deleteMeal(meal)">删除空记录</button></article></div>
     <button class="text-button low-key" @click="simpleInfo('营养参考','原型中的数值是示例。正式版将沿用你的个人参考与计算依据；照片估算不等于实测。')"><Icon name="info"/>查看营养参考</button>
    </template>

    <template v-else-if="page==='capture'">
     <div class="section-heading"><div><h1>记下这一餐</h1><p>拍一张，剩下的交给识别。</p></div></div>
     <div class="photo-preview" :class="{'has-photo':photo}"><img v-if="photo" :src="photo" alt="待记录照片，本地预览"/><template v-else><div class="camera-outline"><Icon name="camera"/></div><h3>把餐食放进画面</h3><p>尽量拍全食物，光线清楚一些</p></template><span v-if="photo" class="photo-caption">仅本地预览 · 不会上传</span></div>
     <div class="two-actions"><label class="primary file-button"><Icon name="camera"/>拍照<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" capture="environment" aria-label="拍摄餐食照片" @change="choosePhoto"/></label><label class="secondary file-button"><Icon name="image"/>从相册选择<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" aria-label="从手机相册选择" @change="choosePhoto"/></label></div>
     <button class="text-button centered" @click="demoPhoto">{{photo?'换成示例照片':'使用示例照片体验'}}<Icon name="arrow"/></button>
     <div class="form-surface"><label>用餐时间<input v-model="pickerTime" type="time" required/></label><label>补充一句（可选）<input v-model="notes" placeholder="例如：米饭只吃了一半"/></label></div><p class="helper">本原型返回固定示例，未进行真实 AI 识别。</p>
     <div class="bottom-action"><button class="primary full" :disabled="!photo" @click="uploadPhoto"><Icon :name="prefs.auto?'camera':'check'"/>{{prefs.auto?'模拟识别这餐':'仅保存示例照片'}}</button></div>
    </template>

    <template v-else-if="page==='meal'&&currentMeal">
     <div class="section-heading"><div><h1>{{currentMeal.name}}</h1><button class="text-button time-edit" @click="editMeal">{{displayDate(currentMeal.date)}} · {{currentMeal.time}}<Icon name="edit"/></button></div><button class="icon-button" aria-label="删除餐食" @click="deleteMeal"><Icon name="trash"/></button></div>
     <img v-if="currentMeal.photo" class="meal-detail-photo" :src="currentMeal.photo" alt="餐食示例照片" width="640" height="480"/>
     <div v-if="currentMeal.status==='processing'" class="processing surface" role="status"><span class="spinner"></span><div><strong>正在整理食物…</strong><p>模拟识别中，可以离开，稍后再看。</p></div></div>
     <div v-else-if="['failed','waiting'].includes(currentMeal.status)" class="status-panel"><Icon name="info"/><div><h3>{{currentMeal.status==='failed'?'这次没有识别成功':'照片已保存'}}</h3><p>{{currentMeal.status==='failed'?'照片仍保留，可以重试或手动添加。':'自动识别已关闭，需要时再发起。'}}</p><button class="secondary" @click="recognize(currentMeal)">{{currentMeal.status==='failed'?'重试模拟识别':'模拟识别照片'}}</button></div></div>
     <div v-else-if="currentMeal.status==='replacement'" class="status-panel"><Icon name="info"/><div><h3>新结果已准备好</h3><p>当前修改尚未被覆盖。</p><button class="secondary" @click="useCandidate">预览替换</button></div></div>
     <div v-if="currentMeal.items.length" class="meal-total"><div><small>这一餐</small><strong>{{sum(currentMeal.items)}}<em>千卡</em></strong></div><span class="quiet-tag"><Icon name="check"/>已保存 · 示例</span></div>
     <p v-if="currentMeal.items.some(f=>f.energy===null)" class="helper">部分营养未知，合计只包含已知数值。</p>
     <div class="food-items"><article v-for="item in currentMeal.items" :key="item.key" class="food-row"><div class="food-thumb"><FoodArt :kind="item.kind"/></div><div class="food-info"><h3>{{item.name}}</h3><p>{{item.energy===null?'营养未知':`${item.energy} 千卡`}}</p><button class="portion-pill" :aria-label="`修改${item.name}份量`" @click="editPortion(item)">{{item.amount}} {{item.unit}}<Icon name="edit"/></button></div><div class="food-row-actions"><button class="icon-button" :aria-label="`移除${item.name}`" @click="removeFood(item)"><Icon name="close"/></button><button class="text-button" :aria-label="`替换${item.name}`" @click="startPicker(currentMeal.id,item.key)">换食物</button></div></article></div>
     <div v-if="!currentMeal.items.length&&currentMeal.status!=='processing'" class="empty small"><Icon name="food"/><p>还没有食物，可以继续补充。</p><button class="text-button danger" @click="deleteMeal">删除空记录</button></div>
     <button class="add-row" @click="startPicker(currentMeal.id)"><Icon name="plus"/>补充食物</button>
     <p v-if="currentMeal.note" class="helper">备注：{{currentMeal.note}}</p>
     <details class="details"><summary>照片与估算说明</summary><p>食物小图为类别插图，不是从照片中分割得到。示例数值不是本图真实营养。</p><p>正式版保留照片、原始识别及后续修改，直到你主动删除。</p><div v-if="currentMeal.photo" class="two-actions"><button class="secondary" :disabled="currentMeal.status==='processing'" @click="recognize(currentMeal)">重新模拟识别</button><button class="text-button danger" @click="openSheet('删除照片？',[],()=>currentMeal.photo=null,{description:'食物记录与识别结果仍保留。示例照片可通过重置恢复。',label:'删除照片',danger:true})">删除照片</button></div></details>
     <div class="bottom-action"><button class="primary full" @click="back"><Icon name="check"/>完成</button></div>
    </template>

    <template v-else-if="page==='picker'">
     <h1>{{replaceKey?'换一种食物':'添加吃过的食物'}}</h1><p class="page-intro">{{replaceKey?'选对食物，再调整份量。':'常吃的放前面，几下就记好。'}}</p>
     <label v-if="!pickerTarget" class="inline-field">{{displayDate(date)}} · 用餐时间<input v-model="pickerTime" type="time" aria-label="手动用餐时间"/></label>
     <label class="search-field"><Icon name="search"/><span class="sr-only">搜索食物</span><input v-model="query" placeholder="白菜、鸡蛋、豆浆…" @input="changeSearch"/><button v-if="query" class="icon-button" aria-label="清空搜索" @click="query='' "><Icon name="close"/></button></label>
     <div class="category-chips" aria-label="食物分类"><button v-for="c in ['常用','全部','主食','肉蛋奶','蔬菜','水果','饮品','家常菜']" :key="c" :class="{selected:category===c}" :aria-pressed="category===c" @click="category=c">{{c==='全部'?'浏览全部':c}}</button></div>
     <div class="section-heading"><h2>{{query?'搜索结果':category==='常用'?'常吃的几样':category==='全部'?'全部食物':category}}</h2><span class="muted">{{matchingFoods.length}} 项</span></div>
     <div class="catalog-list"><article v-for="item in matchingFoods" :key="item.id" class="catalog-row"><button class="catalog-select" :aria-label="`选择${item.name}`" :aria-pressed="selected.some(f=>f.id===item.id)" @click="selectFood(item)"><div class="food-thumb"><FoodArt :kind="item.kind"/></div><div><h3>{{item.name}}</h3><p>{{item.subtitle}}</p><small>{{item.energy??'—'}} 千卡 / {{item.amount}} {{item.unit}}</small></div><span :class="['select-circle',{checked:selected.some(f=>f.id===item.id)}]"><Icon :name="selected.some(f=>f.id===item.id)?'check':'plus'"/></span></button><button class="favorite-button" :aria-label="`${item.common?'取消常用':'设为常用'}${item.name}`" :aria-pressed="item.common" @click="item.common=!item.common"><Icon name="star"/></button></article></div>
     <div v-if="!matchingFoods.length" class="empty small"><Icon name="search"/><h3>没找到“{{query}}”</h3><p>可以换个常见名字，或先记下这份食物。</p></div><button class="text-button centered" @click="customFood"><Icon name="plus"/>补充个人食物</button>
     <section v-if="selected.length&&!replaceKey" class="selected-foods"><div class="section-heading"><h2>已选 {{selected.length}} 项</h2><span class="muted">点份量可修改</span></div><div v-for="item in selected" :key="item.key" class="selected-row"><span>{{item.name}}</span><button class="portion-pill" @click="editPortion(item)">{{item.amount}} {{item.unit}}<Icon name="edit"/></button><button class="icon-button" :aria-label="`取消选择${item.name}`" @click="selected=selected.filter(f=>f.key!==item.key)"><Icon name="close"/></button></div></section>
     <div v-if="!replaceKey" class="bottom-action split"><div><strong>已选 {{selected.length}} 项</strong><small>{{sum(selected)}} 千卡 · 示例</small></div><button class="primary" :disabled="!selected.length" @click="saveSelection">{{pickerTarget?'保存补充':'保存这一餐'}}<Icon name="check"/></button></div>
    </template>

    <template v-else-if="page==='training'">
     <section class="surface training-plan"><div class="section-heading"><span class="quiet-tag">今天的计划</span><button class="text-button" @click="go('plans')">我的计划<Icon name="arrow"/></button></div><template v-if="planAvailable"><div class="training-feature"><div class="exercise-visual"><Icon name="train"/></div><div><h2>全身力量训练</h2><p>{{plan.length}} 个动作 · 按计划量记录</p></div></div><div class="plan-actions"><span>已记录 {{completedSets}} 组 · 剩余 {{remainingSets}} 组</span><button class="text-button" @click="editPlan"><Icon name="edit"/>改计划</button></div><div v-for="(item,i) in plan" :key="item.id" class="exercise-row"><span class="exercise-index">{{String(i+1).padStart(2,'0')}}</span><div><h3>{{item.name}}</h3><p>{{item.sets}} 组 × {{item.reps}} 次<span v-if="item.weight"> · {{item.weight}} kg</span></p></div><span class="progress-count">{{planProgress(item)}} / {{item.sets}} 组</span></div><button class="primary full" @click="beginTraining('plan')"><Icon name="plus"/>按计划记录</button></template><div v-else class="empty small"><Icon name="train"/><h3>今天没有安排</h3><p>可以自由记录，也可以选一个计划。</p><button class="primary" @click="beginTraining('blank')">记录训练</button></div></section>
     <div class="section-heading"><h2>实际练了什么</h2><button class="text-button" @click="beginTraining('blank')"><Icon name="plus"/>添加</button></div>
     <article v-for="record in dayRecords" :key="record.id" class="record-card surface"><div class="section-heading"><span><Icon name="clock"/>{{record.time}}</span><button class="icon-button" aria-label="删除训练记录" @click="deleteTraining(record)"><Icon name="trash"/></button></div><button class="record-body" @click="beginTraining('last',record)"><div><h3>{{record.items.map(i=>i.name).join('、')}}</h3><p>{{record.items.length}} 个动作 · {{record.items.reduce((s,i)=>s+(Number(i.sets)||0),0)}} 组</p></div><Icon name="arrow"/></button></article><p v-if="!dayRecords.length" class="empty-text">还没有训练记录，练完再记也来得及。</p><button class="text-button centered" @click="beginTraining('last')"><Icon name="history"/>使用上次训练内容</button>
    </template>

    <template v-else-if="page==='training-editor'">
     <h1>{{trainingMode==='plan'?'调整今天计划':'记录训练'}}</h1><p class="page-intro">{{trainingMode==='plan'?'只改今天，不影响已经记录的内容。':'按实际做过的填写，整次一起保存。'}}</p><label v-if="trainingMode!=='plan'" class="inline-field">大致时间<input v-model="trainingTime" type="time" aria-label="训练大致时间"/></label>
     <article v-for="(item,index) in trainingDraft" :key="item.id" class="training-edit-card surface"><div class="section-heading"><div><span class="muted">{{String(index+1).padStart(2,'0')}} · {{item.area}}</span><h2>{{item.name}}</h2></div><button class="icon-button" :aria-label="`移除${item.name}`" @click="trainingDraft.splice(index,1)"><Icon name="close"/></button></div><button class="exercise-values" :aria-label="`修改${item.name}`" @click="editExercise(item)"><span><b>{{item.sets??'—'}}</b>组</span><span><b>{{item.reps??'—'}}</b>次 / 组</span><span><b>{{item.weight??'—'}}</b>kg</span><Icon name="edit"/></button></article>
     <button class="add-row" @click="addExercise"><Icon name="plus"/>添加动作</button><p class="helper">数量记不清可以留空，不会当作零。</p><div class="bottom-action"><button class="primary full" :disabled="!trainingDraft.length" @click="saveTraining">{{trainingMode==='plan'?'保存今天计划':'保存训练记录'}}</button></div>
    </template>

    <template v-else-if="page==='plans'">
     <h1>我的计划</h1><p class="page-intro">随时复用，按当天情况调整。</p><article class="surface plan-library"><div class="exercise-visual"><Icon name="train"/></div><h2>全身力量训练</h2><p>{{basePlan.map(i=>i.name).join(' · ')}}</p><div class="two-actions"><button class="primary" @click="planAvailable=true; switchPage('training')">安排到当天</button><button class="secondary" @click="beginTraining('saved'); recordLink=false">直接记录</button></div></article><button class="add-row" @click="editPlan();trainingDraft=[]"><Icon name="plus"/>自定义当天计划</button><button v-if="planAvailable" class="text-button danger centered" @click="openSheet('取消当天安排？',[],()=>{planAvailable=false;switchPage('training')},{description:'已有实际训练记录保留。',label:'取消安排'})">取消当天安排</button>
    </template>

    <template v-else-if="page==='history'">
     <div class="segmented"><button v-for="tab in ['记录','趋势']" :key="tab" :class="{selected:historyTab===tab}" @click="historyTab=tab">{{tab}}</button></div>
     <template v-if="historyTab==='记录'"><label class="history-date"><Icon name="calendar"/><input v-model="historyDate" type="date" aria-label="历史日期"/></label><div class="category-chips"><button v-for="f in ['全部','饮食','训练','身体']" :key="f" :class="{selected:historyFilter===f}" @click="historyFilter=f">{{f}}</button></div><div class="section-heading"><h2>{{displayDate(historyDate)}}</h2><span class="muted">按记录查看</span></div><div class="timeline"><template v-if="['全部','饮食'].includes(historyFilter)"><button v-for="meal in historyMeals" :key="meal.id" class="timeline-row" @click="viewHistoryMeal(meal)"><span class="timeline-icon"><Icon name="food"/></span><div><small>{{meal.time}} · 饮食</small><h3>{{meal.name}}</h3><p>{{meal.items.map(f=>f.name).join('、')}}</p></div><Icon name="arrow"/></button></template><template v-if="['全部','训练'].includes(historyFilter)"><button v-for="record in historyRecords" :key="record.id" class="timeline-row" @click="date=record.date;beginTraining('last',record)"><span class="timeline-icon peach"><Icon name="train"/></span><div><small>{{record.time}} · 训练</small><h3>{{record.items.map(i=>i.name).join('、')}}</h3><p>{{record.items.length}} 个动作</p></div><Icon name="arrow"/></button></template><template v-if="['全部','身体'].includes(historyFilter)"><button v-for="row in historyBody" :key="row.id" class="timeline-row" @click="go('body');editBody(row)"><span class="timeline-icon lavender"><Icon name="scale"/></span><div><small>身体测量</small><h3>{{row.value}} kg</h3><p>体重记录</p></div><Icon name="arrow"/></button></template></div><div v-if="!((['全部','饮食'].includes(historyFilter)&&historyMeals.length)||(['全部','训练'].includes(historyFilter)&&historyRecords.length)||(['全部','身体'].includes(historyFilter)&&historyBody.length))" class="empty"><Icon name="calendar"/><h3>这一天没有相关记录</h3><p>换个日期看看，未记录不代表零。</p></div></template>
     <template v-else><section class="surface body-summary"><small>体重变化 · 示例</small><div class="body-value">{{latestBody?.value??'—'}}<em>kg</em></div><svg viewBox="0 0 320 160" class="trend-chart" role="img" aria-label="示例测量趋势"><path d="M20 40H300M20 90H300M20 140H300" class="chart-grid"/><polyline :points="bodyPoints" class="chart-line"/><circle v-for="point in bodyPoints.split(' ').filter(Boolean)" :key="point" :cx="point.split(',')[0]" :cy="point.split(',')[1]" r="4" class="chart-point"/></svg><div class="chart-labels"><span>9月1日</span><span>9月18日</span></div><button class="text-button centered" @click="go('body')">查看身体记录<Icon name="arrow"/></button></section><p class="helper">只有真实记录点才参与连线。正式版保留饮食、训练各自适用的趋势。</p><button class="setting-row" @click="simpleInfo('饮食趋势','本轮先展示身体趋势交互。正式版保留逐日已记录的四项营养，不把缺失日期补成零。')"><Icon name="food"/><span>饮食营养趋势</span><Icon name="arrow"/></button><button class="setting-row" @click="simpleInfo('训练趋势','正式版按记录日期和具体动作查看，不混合不同动作的总量。此处为原型说明。')"><Icon name="train"/><span>训练记录趋势</span><Icon name="arrow"/></button></template>
    </template>

    <template v-else-if="page==='profile'">
     <div class="profile-heading"><span class="avatar large">我</span><div><h2>{{profileName}}</h2><p>{{profileGoal}} · 示例资料</p></div><button class="icon-button" aria-label="编辑个人资料" @click="renameProfile"><Icon name="edit"/></button></div>
     <section class="surface body-summary"><div class="section-heading"><h2>我的身体</h2><button class="text-button" @click="go('body')">查看趋势<Icon name="arrow"/></button></div><div class="body-summary-row"><div><small>最近体重</small><div class="body-value">{{latestBody?.value??'—'}}<em>kg</em></div><small>{{latestBody?`${displayDate(latestBody.date)}测量`:'尚未记录'}}</small></div><div class="body-symbol"><Icon name="scale"/></div></div><button class="primary full" @click="editBody()"><Icon name="plus"/>记录体重</button></section>
     <section class="settings-list surface"><button class="setting-row" @click="renameProfile"><Icon name="user"/><span>资料与目标<small>{{profileGoal}}</small></span><Icon name="arrow"/></button><button class="setting-row" @click="go('settings')"><Icon name="settings"/><span>应用设置<small>识别偏好、提醒和账号</small></span><Icon name="arrow"/></button></section><button class="text-button centered" @click="go('prototype')">原型说明与场景切换</button>
    </template>

    <template v-else-if="page==='body'">
     <div class="section-heading"><h1>身体记录</h1><button class="icon-button" aria-label="新增体重" @click="editBody()"><Icon name="plus"/></button></div><section class="surface body-summary"><small>最近一次</small><div class="body-value">{{latestBody?.value??'—'}}<em>kg</em></div><svg viewBox="0 0 320 160" class="trend-chart" role="img" aria-label="示例体重趋势"><path d="M20 40H300M20 90H300M20 140H300" class="chart-grid"/><polyline :points="bodyPoints" class="chart-line"/><circle v-for="point in bodyPoints.split(' ').filter(Boolean)" :key="point" :cx="point.split(',')[0]" :cy="point.split(',')[1]" r="4" class="chart-point"/></svg></section><div class="section-heading"><h2>测量记录</h2><span class="muted">{{measurements.length}} 次</span></div><div v-for="row in [...measurements].sort((a,b)=>b.date.localeCompare(a.date))" :key="row.id" class="measurement-row"><span>{{displayDate(row.date)}}</span><strong>{{row.value}}<em>kg</em></strong><button class="icon-button" :aria-label="`修改${row.date}测量`" @click="editBody(row)"><Icon name="edit"/></button><button class="icon-button" :aria-label="`删除${row.date}测量`" @click="deleteBody(row)"><Icon name="trash"/></button></div><div v-if="!measurements.length" class="empty small"><p>还没有身体测量</p></div><div class="bottom-action"><button class="primary full" @click="editBody()"><Icon name="plus"/>记录新测量</button></div>
    </template>

    <template v-else-if="page==='settings'">
     <h1>应用设置</h1><h2 class="group-title">记录偏好</h2><section class="surface settings-list"><div class="setting-row"><Icon name="camera"/><span>照片自动识别<small>只影响之后选择的照片</small></span><label class="switch"><input v-model="prefs.auto" type="checkbox" aria-label="照片自动识别" @change="toggleAuto"/><span></span></label></div><div class="setting-row"><Icon name="bell"/><span>记录提醒<small>训练、饮食与身体测量</small></span><label class="switch"><input v-model="prefs.reminder" type="checkbox" aria-label="记录提醒"/><span></span></label></div><label v-if="prefs.reminder" class="inline-field">提醒时间<input type="time" value="20:00" aria-label="提醒时间"/></label></section><h2 class="group-title">账号与数据</h2><section class="surface settings-list"><button class="setting-row" @click="simpleInfo('修改密码','这是界面原型，不接收真实密码。正式版会验证当前密码后修改。')"><Icon name="shield"/><span>修改密码</span><Icon name="arrow"/></button><button class="setting-row" @click="simpleInfo('导出记录','此处仅展示入口，不生成或下载真实数据。正式版沿用已有导出进度与下载功能。')"><Icon name="download"/><span>导出记录</span><Icon name="arrow"/></button><button class="setting-row" @click="simpleInfo('问题反馈','正式版由你主动预览并分享问题报告，不自动上传照片或健康明细。')"><Icon name="info"/><span>帮助与反馈</span><Icon name="arrow"/></button></section><button class="secondary full" @click="signupStep=0;authMode='login';go('signup')"><Icon name="logout"/>退出示例账号</button><button class="text-button danger centered" @click="simpleInfo('删除账号','真实删除需验证身份并再次确认。本原型不会删除任何真实账号或数据。')">删除账号</button>
    </template>

    <template v-else-if="page==='signup'">
     <div class="signup-mark"><Icon name="leaf"/></div><p class="eyebrow">Exercise App</p><h1>{{signupStep===0?(authMode==='login'?'欢迎回来':'从今天，轻松记录'):['','先认识一下你','记录身体起点','你想朝哪个方向','需要提醒你吗？'][signupStep]}}</h1><p class="page-intro">{{signupStep===0?'饮食与训练，按自己的节奏。':`首次设置 · ${signupStep} / 4`}}</p>
     <form class="signup-form" @submit.prevent="authMode==='login'&&signupStep===0?switchPage('today'):signupNext()"><template v-if="signupStep===0"><label>用户名<input v-model="signup.name" autocomplete="off" placeholder="仅供体验，不创建真实账号" required/></label><label>密码（请勿填真实密码）<input v-model="signup.password" type="password" autocomplete="new-password" placeholder="原型使用任意示例密码" required/></label><section v-if="authMode==='register'" class="consent-card"><label class="checkbox-row"><input v-model="signup.auto" type="checkbox"/><span><strong>开启照片自动识别</strong><small>拍照后帮你整理食物和份量，可随时关闭。</small></span></label><p>正式版会把所选照片发送给模型服务。照片和修改过程保留至主动删除。</p><label v-if="signup.auto" class="checkbox-row"><input v-model="signup.consent" type="checkbox" required/><span>我同意上述照片发送范围</span></label></section></template><template v-else-if="signupStep===1"><label>怎么称呼你<input v-model="signup.name" required/></label><label>日常活动<select v-model="signup.activity"><option>大部分时间坐着</option><option>日常走动较多</option><option>体力活动较多</option></select></label><p class="helper">原型简化展示；正式版保留计算所需资料与无法提供的选项。</p></template><template v-else-if="signupStep===2"><label>身高 cm<input v-model="signup.height" type="number" min="50" max="250" placeholder="例如 170" required/></label><label>体重 kg<input v-model="signup.weight" type="number" min="20" max="500" step=".1" placeholder="例如 65.4" required/></label></template><template v-else-if="signupStep===3"><label v-for="goal in ['减少体重','保持体重','增加体重']" :key="goal" :class="['goal-choice',{chosen:signup.goal===goal}]"><input v-model="signup.goal" type="radio" :value="goal"/>{{goal}}<Icon v-if="signup.goal===goal" name="check"/></label></template><template v-else><label class="checkbox-row"><input v-model="signup.reminder" type="checkbox"/><span>开启记录提醒</span></label><p class="helper">可以跳过，以后在应用设置里调整。原型不会申请通知权限。</p></template><button class="primary full" type="submit">{{signupStep===0?(authMode==='login'?'进入示例账号':'注册并继续'):signupStep===4?'完成设置':'下一步'}}<Icon name="arrow"/></button><button v-if="signupStep===4" class="text-button centered" type="button" @click="signup.reminder=false;finishSignup()">跳过提醒</button><button v-if="signupStep>0" class="text-button centered" type="button" @click="signupStep--">上一步</button><button v-if="signupStep===0" class="text-button centered" type="button" @click="authMode=authMode==='login'?'register':'login'">{{authMode==='login'?'体验注册流程':'已有账号，去登录'}}</button></form>
    </template>

    <template v-else-if="page==='prototype'">
     <h1>原型体验</h1><p class="page-intro">所有数据仅存在当前页面内存。刷新即可恢复，不连接任何业务服务。</p><section class="surface prototype-options"><h2>异常场景</h2><label>当前场景<select v-model="scenario"><option value="normal">正常流程</option><option value="upload-failed">上传失败</option><option value="recognition-failed">识别失败</option><option value="save-failed">保存失败（保留输入）</option></select></label><button class="secondary full" @click="startCapture">体验照片记录</button><button class="secondary full" @click="setEmpty">查看无记录日期</button><button class="secondary full" @click="signupStep=0;authMode='register';go('signup')">体验注册与首次设置</button><button class="text-button centered" @click="resetDemo"><Icon name="refresh"/>重置示例记录</button></section><details class="details"><summary>素材、边界与说明</summary><p>餐盘图来自 Nutrition5k（Google Research / Thames et al., CVPR 2021，CC BY 4.0），仅作公开示例。食物插图为原创类别示意。图片和营养示例不作为真实对应关系或营养建议。</p><p>未实现真实拍照识别、通知、导出、账号操作和生产 API 接入。照片本地预览不上传。</p></details>
    </template>
   </main>
   <nav v-if="mainPage" class="bottom-nav" aria-label="主要导航"><button v-for="item in nav" :key="item.id" :class="{active:active===item.id}" :aria-current="active===item.id?'page':undefined" @click="switchPage(item.id)"><span><Icon :name="item.icon"/></span>{{item.label}}</button></nav>
  </div>
  <dialog ref="dialog" class="sheet" aria-labelledby="sheet-title" @click="event=>event.target===dialog&&closeSheet()"><form @submit.prevent="submitSheet"><div class="sheet-handle"></div><div class="section-heading"><h2 id="sheet-title">{{sheet.title}}</h2><button class="icon-button" type="button" aria-label="关闭弹层" @click="closeSheet"><Icon name="close"/></button></div><p v-if="sheet.description" class="sheet-description">{{sheet.description}}</p><label v-for="f in sheet.fields" :key="f.name">{{f.label}}<select v-if="f.type==='select'" v-model="f.value"><option v-for="option in f.options" :key="option">{{option}}</option></select><input v-else v-model="f.value" :type="f.type" :min="f.min" :max="f.max" :step="f.step" :required="f.required"/></label><p v-if="sheet.error" class="error-text" role="alert">{{sheet.error}}</p><button v-if="sheet.error" type="button" class="text-button" @click="scenario='normal';submitSheet()">恢复正常并重试</button><div class="sheet-footer"><button class="secondary" type="button" @click="closeSheet">取消</button><button :class="['primary',{destructive:sheet.danger}]" type="submit">{{sheet.label}}</button></div></form></dialog>
 </div>
</template>
