// Generated by scripts/generate-food-catalog.py; do not hand-edit nutrient values.
// USDA FoodData Central, SR Legacy April 2018; CC0 1.0.
// Official CSV archive SHA256: b80817294b8850530aaedf2e515c02593b1824f763a0ff356e5c2081643e6fd0
export const usdaFoods = [
  {
    "fdcId": 168463,
    "label": "菠菜（水煮、沥干、无盐）",
    "category": "vegetables",
    "originalName": "Spinach, cooked, boiled, drained, without salt",
    "energyKcal": 23.0,
    "proteinGrams": 2.97,
    "carbohydrateGrams": 3.75,
    "fatGrams": 0.26
  },
  {
    "fdcId": 168878,
    "label": "白米饭（长粒、强化米、熟）",
    "category": "grains",
    "originalName": "Rice, white, long-grain, regular, enriched, cooked",
    "energyKcal": 130.0,
    "proteinGrams": 2.69,
    "carbohydrateGrams": 28.17,
    "fatGrams": 0.28
  },
  {
    "fdcId": 169967,
    "label": "西兰花（水煮、沥干、无盐）",
    "category": "vegetables",
    "originalName": "Broccoli, cooked, boiled, drained, without salt",
    "energyKcal": 35.0,
    "proteinGrams": 2.38,
    "carbohydrateGrams": 7.18,
    "fatGrams": 0.41
  },
  {
    "fdcId": 170394,
    "label": "胡萝卜（水煮、沥干、无盐）",
    "category": "vegetables",
    "originalName": "Carrots, cooked, boiled, drained, without salt",
    "energyKcal": 35.0,
    "proteinGrams": 0.76,
    "carbohydrateGrams": 8.22,
    "fatGrams": 0.18
  },
  {
    "fdcId": 170440,
    "label": "土豆（去皮水煮、无盐）",
    "category": "grains",
    "originalName": "Potatoes, boiled, cooked without skin, flesh, without salt",
    "energyKcal": 86.0,
    "proteinGrams": 1.71,
    "carbohydrateGrams": 20.01,
    "fatGrams": 0.1
  },
  {
    "fdcId": 171284,
    "label": "原味全脂酸奶",
    "category": "dairy",
    "originalName": "Yogurt, plain, whole milk",
    "energyKcal": 61.0,
    "proteinGrams": 3.47,
    "carbohydrateGrams": 4.66,
    "fatGrams": 3.25
  },
  {
    "fdcId": 171413,
    "label": "橄榄油",
    "category": "fats",
    "originalName": "Oil, olive, salad or cooking",
    "energyKcal": 884.0,
    "proteinGrams": 0.0,
    "carbohydrateGrams": 0.0,
    "fatGrams": 100.0
  },
  {
    "fdcId": 171477,
    "label": "鸡胸肉（去皮、烤熟）",
    "category": "meat_eggs",
    "originalName": "Chicken, broilers or fryers, breast, meat only, cooked, roasted",
    "energyKcal": 165.0,
    "proteinGrams": 31.02,
    "carbohydrateGrams": 0.0,
    "fatGrams": 3.57
  },
  {
    "fdcId": 171688,
    "label": "苹果（带皮、生）",
    "category": "fruit",
    "originalName": "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
    "energyKcal": 52.0,
    "proteinGrams": 0.26,
    "carbohydrateGrams": 13.81,
    "fatGrams": 0.17
  },
  {
    "fdcId": 172217,
    "label": "全脂牛奶（3.25%乳脂、无额外强化）",
    "category": "dairy",
    "originalName": "Milk, whole, 3.25% milkfat, without added vitamin A and vitamin D",
    "energyKcal": 61.0,
    "proteinGrams": 3.15,
    "carbohydrateGrams": 4.78,
    "fatGrams": 3.27
  },
  {
    "fdcId": 172446,
    "label": "豆奶（原味/香草、无强化）",
    "category": "beans",
    "originalName": "Soymilk, original and vanilla, unfortified",
    "energyKcal": 54.0,
    "proteinGrams": 3.27,
    "carbohydrateGrams": 6.28,
    "fatGrams": 1.75
  },
  {
    "fdcId": 172476,
    "label": "豆腐（硫酸钙凝固、生）",
    "category": "beans",
    "originalName": "Tofu, raw, regular, prepared with calcium sulfate",
    "energyKcal": 76.0,
    "proteinGrams": 8.08,
    "carbohydrateGrams": 1.87,
    "fatGrams": 4.78
  },
  {
    "fdcId": 172688,
    "label": "全麦面包（市售）",
    "category": "grains",
    "originalName": "Bread, whole-wheat, commercially prepared",
    "energyKcal": 252.0,
    "proteinGrams": 12.45,
    "carbohydrateGrams": 42.71,
    "fatGrams": 3.5
  },
  {
    "fdcId": 173424,
    "label": "鸡蛋（水煮全蛋）",
    "category": "meat_eggs",
    "originalName": "Egg, whole, cooked, hard-boiled",
    "energyKcal": 155.0,
    "proteinGrams": 12.58,
    "carbohydrateGrams": 1.12,
    "fatGrams": 10.61
  },
  {
    "fdcId": 173806,
    "label": "花生（干烤、无盐）",
    "category": "fats",
    "originalName": "Peanuts, all types, dry-roasted, without salt",
    "energyKcal": 587.0,
    "proteinGrams": 24.35,
    "carbohydrateGrams": 21.26,
    "fatGrams": 49.66
  },
  {
    "fdcId": 173944,
    "label": "香蕉（生）",
    "category": "fruit",
    "originalName": "Bananas, raw",
    "energyKcal": 89.0,
    "proteinGrams": 1.09,
    "carbohydrateGrams": 22.84,
    "fatGrams": 0.33
  }
] as const;
