import { randomUUID } from "node:crypto";
import { expect } from "vitest";
import { PlanningService, emptyProfile, defaultStrategy } from "../modules/planning/service.js";
import type { PlanningRepository } from "../modules/planning/repository.js";

export async function verifyOnboardingBody(repository: PlanningRepository, owner: string, other: string) {
  const service = new PlanningService(repository, () => new Date("2026-09-16T04:00:00Z"));
  expect(await service.getSetupProgress(owner)).toEqual({ profile: false, measurement: false, strategy: false, completed: false });
  await expect(service.advanceSetup(owner, "finish")).rejects.toMatchObject({ statusCode: 400 });
  await service.advanceSetup(owner, "start");
  await service.updateProfile(owner, (await service.getProfile(owner)).revision, emptyProfile);
  await service.advanceSetup(owner, "profile");
  const resumed = new PlanningService(repository);
  expect(await resumed.getSetupProgress(owner)).toMatchObject({ profile: true, measurement: false, completed: false });
  await expect(service.advanceSetup(owner, "measurement")).rejects.toMatchObject({ statusCode: 400 });
  await service.advanceSetup(owner, "measurement", true);
  await service.updateStrategy(owner, 0, defaultStrategy);
  await service.advanceSetup(owner, "strategy");
  expect((await service.getSetupProgress(owner)).completed).toBe(false);
  await Promise.all([service.advanceSetup(owner, "finish"), service.advanceSetup(owner, "start")]);
  expect((await resumed.getSetupProgress(owner)).completed).toBe(true);
  expect((await service.getSetupProgress(other)).completed).toBe(false);
  expect(await service.listMeasurements(owner)).toEqual([]);
  const input = { measuredAt: "2026-09-15T23:00:00Z", localDate: "2026-09-15", timeZone: "Asia/Shanghai", weightKg: 70.126, waistCm: 80.125, note: "测试测量" };
  const id = randomUUID();
  const [created, retry] = await Promise.all([service.updateMeasurement(owner, id, 0, input), service.updateMeasurement(owner, id, 0, input)]);
  expect(created.revision).toBe(1); expect(retry.id).toBe(created.id);
  expect(created.weightKg).toBe(70.13); expect(created.waistCm).toBe(80.13);
  await expect(service.updateMeasurement(owner, id, 0, { ...input, weightKg: 72 })).rejects.toMatchObject({ statusCode: 409 });
  await expect(service.updateMeasurement(other, id, 0, input)).rejects.toMatchObject({ statusCode: 404 });
  await expect(service.deleteMeasurement(other, id, 1)).rejects.toMatchObject({ statusCode: 404 });
  const backdated = await service.createMeasurement(owner, { ...input, localDate: "2026-08-01", measuredAt: "2026-09-16T04:00:00Z", weightKg: 80 });
  expect((await service.listMeasurements(owner))[0]?.id).toBe(id);
  expect((await repository.getLatestMeasurement(owner, "2026-09-16"))?.id).toBe(id);
  const historic = await service.getDailyReference(owner, "2026-09-15", "Asia/Shanghai");
  const corrected = await service.updateMeasurement(owner, id, 1, { ...input, weightKg: 71 });
  expect(corrected.measuredAt).toEqual(created.measuredAt);
  expect((await service.updateMeasurement(owner, id, 1, { ...input, weightKg: 71 })).revision).toBe(2);
  await expect(service.deleteMeasurement(owner, id, 1)).rejects.toMatchObject({ statusCode: 409 });
  await service.deleteMeasurement(owner, id, 2);
  await service.deleteMeasurement(owner, id, 2);
  await expect(service.updateMeasurement(owner, id, 0, input)).rejects.toMatchObject({ statusCode: 404 });
  await expect(service.updateMeasurement(owner, id, 2, input)).rejects.toMatchObject({ statusCode: 404 });
  expect((await service.listMeasurements(owner)).map(value => value.id)).toEqual([backdated.id]);
  expect((await repository.getLatestMeasurement(owner, "2026-09-16"))?.id).toBe(backdated.id);
  expect((await service.getDailyReference(owner, "2026-09-15", "Asia/Shanghai")).id).toBe(historic.id);
  expect(historic.inputSnapshot.measurement?.weightKg).toBe(70.13);
  expect(await service.listMeasurementRevisions(owner, id)).toHaveLength(2);
  expect((await service.getSetupProgress(owner)).completed).toBe(true);
  expect(await service.listMeasurements(other)).toEqual([]);
}
