"""Generate the reviewed SR Legacy subset from the official, unmodified CSV zip.

Usage: python3 apps/server/scripts/generate-food-catalog.py /path/to/sr.zip
No network, account data, or inferred nutrient values are used.
"""
import csv
import hashlib
import io
import json
from pathlib import Path
import sys
import zipfile

SELECTION = {
    168463: ("菠菜（水煮、沥干、无盐）", "vegetables"),
    168878: ("白米饭（长粒、强化米、熟）", "grains"),
    169967: ("西兰花（水煮、沥干、无盐）", "vegetables"),
    170394: ("胡萝卜（水煮、沥干、无盐）", "vegetables"),
    170440: ("土豆（去皮水煮、无盐）", "grains"),
    171284: ("原味全脂酸奶", "dairy"),
    171413: ("橄榄油", "fats"),
    171477: ("鸡胸肉（去皮、烤熟）", "meat_eggs"),
    171688: ("苹果（带皮、生）", "fruit"),
    172217: ("全脂牛奶（3.25%乳脂、无额外强化）", "dairy"),
    172446: ("豆奶（原味/香草、无强化）", "beans"),
    172476: ("豆腐（硫酸钙凝固、生）", "beans"),
    172688: ("全麦面包（市售）", "grains"),
    173424: ("鸡蛋（水煮全蛋）", "meat_eggs"),
    173806: ("花生（干烤、无盐）", "fats"),
    173944: ("香蕉（生）", "fruit"),
}

archive = Path(sys.argv[1])
prefix = "FoodData_Central_sr_legacy_food_csv_2018-04/"
with zipfile.ZipFile(archive) as z:
    def rows(name):
        return csv.DictReader(io.TextIOWrapper(z.open(prefix + name), encoding="utf-8-sig"))

    foods = {int(r["fdc_id"]): r for r in rows("food.csv") if int(r["fdc_id"]) in SELECTION}
    nutrients = {i: {} for i in SELECTION}
    keys = {1008: "energyKcal", 1003: "proteinGrams", 1005: "carbohydrateGrams", 1004: "fatGrams"}
    for r in rows("food_nutrient.csv"):
        food_id, nutrient_id = int(r["fdc_id"]), int(r["nutrient_id"])
        if food_id in nutrients and nutrient_id in keys:
            key = keys[nutrient_id]
            if key in nutrients[food_id]:
                raise ValueError(f"Duplicate nutrient: {food_id}/{nutrient_id}")
            nutrients[food_id][key] = float(r["amount"]) if r["amount"] else None

assert set(foods) == set(SELECTION)
items = [{"fdcId": i, "label": name, "category": category, "originalName": foods[i]["description"],
          **{key: nutrients[i].get(key) for key in keys.values()}} for i, (name, category) in SELECTION.items()]
digest = hashlib.sha256(archive.read_bytes()).hexdigest()
target = Path(__file__).resolve().parents[1] / "src/modules/nutrition/usda-foods.generated.ts"
target.write_text(
    "// Generated by scripts/generate-food-catalog.py; do not hand-edit nutrient values.\n"
    "// USDA FoodData Central, SR Legacy April 2018; CC0 1.0.\n"
    f"// Official CSV archive SHA256: {digest}\n"
    "export const usdaFoods = " + json.dumps(items, ensure_ascii=False, indent=2) + " as const;\n", encoding="utf-8")
print(f"Generated {len(items)} foods; source SHA256 {digest}")
